### ISSUE TITLE
Allow sub jobs to be tracked by which 'main' job they relate to

### ISSUE THREAD

**Issue by gillins** [ubarsc/rios#111]
Currently, with AWS Batch when you start a few jobs that also spawn AWS Batch worker jobs there is no way of working out which worker job belongs to which man job apart from attempting to match start times.
They currently all get called `RIOS_X` where X is in the order that the job was started. Would it be possible to pass through some sort of unique string which can be prepended to this name here: https://github.com/ubarsc/rios/blob/master/rios/computemanager.py#L277 ?

Could this also be done for SLURM and PBS?

**Comment by neilflood** [comment]
This seems like a good suggestion. There are some details to figure out, though.

So, you would want a string that was unique for each separate run of the main script, but the user needs to be able to know what is is, in order to be able to tie the worker jobs to the originating job. Would the process ID of the main script be appropriate? This would give names like `RIOS_12345_0`, being worker number 0 from main script number 12345. A process ID seems like something that would always be available, but would the user be able to see it easily enough? Perhaps there is a Batch job ID number that would make more sense?

I am not sure what would make sense for the PBS and/or SLURM cases, but we can investigate.

I agree that this would become an issue, once you start to have multiple jobs running.

**Comment by gillins** [comment]
Process ID not going to work because things are running on different machines (and machines we can't easily get access to).

For submitting my main script I come up with a unique name based on inputs/parameters etc. I'd like to pass that name in so the sub jobs have that in their name too. So if something falls over I know what else to kill and what to restart etc.

Yes indeed an issue with multiple jobs running :smile:

For SLURM I was thinking using `--job-name`. I don't think we do, but perhaps we should default this to `RIOS_X` at the very least so a user can see what are the sub jobs running. But would be nice to be able to prepend a similar string...

**Comment by neilflood** [comment]
OK, that all makes sense. I think something like this should be doable. The biggest hurdle in my head right now is what to call this string. Something like `mainScriptJobIDstring`, which seems absurdly cumbersome, especially when tacked onto a controls.set method (`controls.setMainScriptJobIDstring(mainScriptJobIDstring)` is going to be a bit much.....). Naming things is often the hardest bit.......

However, a string which the main script could work out, passed in on the controls object, and then apply() would pass it on to the computeMgr object, which can in turn do something with it, specific to the computeWorkerKind. That all seems to hang together, I think. 

So, what to call it...... sigh......

**Comment by gillins** [comment]
`jobIDPrefix`?

**Comment by neilflood** [comment]
Fixed by #113
