### ISSUE TITLE
Stop vendoring cloudpickle

### ISSUE THREAD

**Issue by gillins** [ubarsc/rios#62]
Just a thought - since there are now regular fixes for new Python versions upstream (see https://github.com/cloudpipe/cloudpickle/commits/master) maybe we should stop trying to vendor our own version and always be out of date. The rate of Python internal changes does seem to be increasing...
Both [conda-forge](https://github.com/conda-forge/cloudpickle-feedstock) and [Ubuntu](https://packages.ubuntu.com/kinetic/python3-cloudpickle) provide packages for `cloudpickle`. Of course you can also `pip install` it so not really hard for a user to obtain. 
How about we remove it from `rios` and expect the user to have it installed if they are using the `parallel` functionality (users who aren't will see no difference)?

I can modify the conda-forge recipe to install it when `rios` is installed.

**Comment by neilflood** [comment]
I agree with this. When we first started doing things with cloudpickle, it was a bit more niche, but it has since become much more widely used. I think we can rely on it to be available from standard sources, if the user wants, and so we can probably stop including our own copy. 

Very good, thank you.

**Comment by gillins** [comment]
I'll submit a PR for this after #61 is merged.
